# ウェブサイト名
title: あゆき's BLOG
# ウェブサイトのタイトルの接尾辞
suffix: Next
# 作者名(CopyRightなどに使用)
author: TeamPimcServer
# サイト説明
home_describe: A STUDENT WITH IDEALS AND BELIEFS.
# サイトのキーワード
keyword: hexo, あゆき's Blog, ayuki's blog
is_article_img: false  #false是否开启文章背景图显示(随机图片)
# ogp
web_description: あきとゆぴによる気ままな共同ブログ
# メニューの名前
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# メニューのURL
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# ロゴ
logo: /image/logo.webp
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "/image/logo.webp"
  archivesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
  tagIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
  linksIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
  categoriesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
  
# 标签页显示多少个标签
tagsNum: 1000
# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fa  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/TeamPimcServer/ayuki_blog'
  }
# リンク
linksList:
  - {
    title: 'ゆぴ',
    intro: '本サイトでのテンプレートのデザインに手を加えたり、独自のデザインを追加している人です。主にMinecraftServerを運営しています',
    link: 'https://ne.akarinext.org/@yupix',
    image: 'https://s3.akarinext.org/assets/*/yupix-icon.png'
  }
  - {
    title: 'あき',
    intro: '主にMinecraftServerを運営しています',
    link: 'https://xe.akirin.xyz/@aki',
    image: 'https://s3.akarinext.org/assets/*/aki-icon.png'
  }
  - {
    title: 'TeamPimcServer',
    intro: '本blogの開発メンバーが運営しているチームです',
    link: 'https://discord.gg/CcT997U',
    image: '/image/pimc_logo.png'
  }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#333'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: https://s3.akarinext.org/assets/*/NOT%20FOUND.png