# ウェブサイト名
title: あゆき's BLOG
# ウェブサイトのタイトルの接尾辞
suffix: あゆき's BLOG
# 作者名(CopyRightなどに使用)
author: TeamPimcServer
# サイト説明
home_describe: A STUDENT WITH IDEALS AND BELIEFS.
# サイトのキーワード
keyword: hexo, あゆき's Blog, ayuki's blog
is_article_img: true  #false是否开启文章背景图显示(随机图片)
# ogp
web_description: あきとゆぴによる気ままな共同ブログ
# メニューの名前
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# メニューのURL
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# ロゴ
logo: /image/logo.webp
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "/image/logo.webp"
  archivesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
  tagIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
  linksIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
  categoriesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
  
# 标签页显示多少个标签
tagsNum: 1000
# 网页访问统计


headers:
    home: {
      message: "A STUDENT WITH IDEALS AND BELIEFS.",
      icon: "/image/logo.webp"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "year 年で number 個の記事を作成しました",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
    }
    tags: {
      message: "タグ一覧",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
    }
    links: {
      message: "本ブログの著者たち",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
    }
    categories: {
      message: "カテゴリ一覧",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
    }

gitalk:
  clientID: defaultGitalkClientID # どうするか検討
  clientSecret: defaultGitalkClientSecret
  repo: ayuki_blog
  owner: TeamPimcServer
  admin: ['yupix', 'sousuke0422']


bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/TeamPimcServer/ayuki_blog'
  }
# リンク
linksList:
  - {
    title: 'ゆぴ',
    intro: '本サイトでのテンプレートのデザインに手を加えたり、独自のデザインやJavaScriptを追加している人です。他にはMinecraftServerを運営しています',
    link: 'https://ne.akarinext.org/@yupix',
    image: '/image/icon/yupix.webp'
  }
  - {
    title: 'あき',
    intro: '主にAyuskeyの開発などを行っています。フロントエンドかバックエンド開発者かでいうとバックエンド開発者です。',
    link: 'https://kr.akirin.xyz/@aki',
    image: '/image/icon/aki.webp'
  }
  - {
    title: 'TeamPimcServer',
    intro: '本Blogを運営しているチームのアカウントです。Blogに関する告知などはこのアカウントで行います。',
    link: 'https://discord.gg/CcT997U',
    image: '/image/icon/pimc-logo.svg'
  }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#333'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: /image/imagenotfound.svg