language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GT_TOKEN # セキュアとマークされたアクセストークンを travis-ci.org のダッシュボードに設定してください。https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  local_dir: docs-dist
  keep_history: true
  on:
    branch: master

env:
  global:
    - secure: "+NY4/RSG2nymHxVTSTs34AEOcKU2DWHYofDvyCVfvC0VrU6HGfgC+qRpuBMGhUQ36peoINqKt9bxLqT1nRLPojNpGCpY64G8Zri1dp5gf+LwySouJE1hwSLDUj3pdC2AIQVbcTMoad6wfQolLL3aAzBzv2ZODk4M3LDfQUjZJI1Qbwe6/u1DkWfTVHX1HCH5TN8P2m+ovrw8SvImoo3PWHC0Jl/A84TmIOIhV+R/VBVEF9FSw4JqQcVuo/bf7zvaaAHb4V2dnsd9QCG5cYuI9Bcy9AYE0gofum+jgjhT0Zs9w6mBuLWLzi86siIwOD178Q1E+3bVcYALPlBt8vpEb1TqHvh+Vt5EPpm/Dvw0juezk8Qx2S88NhyRl4G/J8T47ZuhC6+JtQS6NNqOezJrskj8u2n7R0orsbAy6eOesXR+f2rjZlodiZyfqXStX6iXrvg0eC9qMF5AyvJoFrg1fxQJflXYXh6ns4c/59LZJKbbNjZ1BJRmwSYzekO/E+PMpzNKFag9jNLVW2nJKepL7SfGp1jCpJwW2tEnyE19+GOVsqF4NljkZcji6ujJ+QAFrn9VjCEjWJTs+EkVXH1NQ6k5ChF9XvDVErzupUqpkhghcELtSHYiSgKzUoHmLQOwU9hNe97VzGqV/rf0chGXdTfQwQLlGIL9eqCMaXi95eE="

notifications:
  email: false
