language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # セキュアとマークされたアクセストークンを travis-ci.org のダッシュボードに設定してください。https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  local_dir: docs-dist
  keep_history: true
  on:
    branch: master

notifications:
  email: false
