name: Build and Deploy

on:
  push:
    branches:
      - master  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache
          restore-keys: |
            ${{ runner.OS }}-yarn-cache

      - name: Install Package and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install locales fonts-ipafont fonts-ipaexfont
          sudo sh -c "echo ja_JP UTF-8 > /etc/locale.gen"
          locale-gen
          yarn install

      - name: Build
        run: yarn run build

      - name: Cache cover image
        uses: actions/cache@v2
        with:
          path: .covers
          key: ${{ runner.OS }}-cover-image-cache
          restore-keys: ${{ runner.OS }}-cover-image-cache

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages 
